config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "meets#index"
  resources :meets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/meet.rb
class Meet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  

end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController

  def index
    @meets = Meet.all
  end

  def new
    @meet = Meet.new
  end

  def show
    @meet = Meet.find(params[:id])
    @comments = Comment.all
  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def create
    @meet = Meet.new(meet_params)
    if @meet.save
      redirect_to meets_path
    else
      render :new
    end
  end

  def update
    @meet = Meet.find(params[:id])
    if @meet.update(meet_params)
      redirect_to meet_path(@meet)
    else
      render :edit
    end
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy
    redirect_to meets_path
  end

  private

  def meet_params
    params.require(:meet).permit(:title, :info)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="content">
    <%= comment.content %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main_content">
      <div id="header">
          <button class="button"><%= link_to "New Meetup", new_meet_path %></button>
        <% if !current_user %>
          <button class="button"><%= link_to "Login", new_user_session_path %></button>
        <% else %>
          <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/meets/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
      <h2 class="text-center">New meetup</h2>
      <%= simple_form_for @meet do |f| %>
        <%= f.input :title %>
        <%= f.input :info %>
        <%= f.submit "更新meetup", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-3">

    </div>
  </div>
</div>

app/views/meets/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div class="meetup">
        <% @meets.each do |meet| %>
          <div class="title">
            <%= link_to meet.title, meet_path(meet) %>
          </div>
          <div class="info">
            <%= meet.info %>
          </div>
        <% end %>
        <hr>
      </div>
    </div>
    <div class="col-md-2">

    </div>
  </div>
</div>

app/views/meets/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
      <h2 class="text-center">New meetup</h2>
      <%= simple_form_for @meet do |f| %>
        <%= f.input :title %>
        <%= f.input :info %>
        <%= f.submit "新增meetup", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-3">

    </div>
  </div>
</div>

app/views/meets/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div class="meetup">
        <div class="title">
          <%= @meet.title %>
        </div>
        <div class="info">
          <%= @meet.info %>
        </div>
        <% @comments.each do |comment| %>
          <%= render @meet.comments %>
        <% end %>
      </div>
    </div>
    <div class="col-md-2">
      <button class="button"><%= link_to "Edit", edit_meet_path(@meet) %></button>
      <button class="button"><%= link_to "Delete", meet_path(@meet), method: :delete, data: { confirm: "Are you sure?" } %></button>
    </div>
  </div>
</div>